# get_estimates.R
# Fits the oscillator to one dataset and tidies the parameters dynr estimated.
# takes the object generated by get_dataset()

library(dynr)

# The parameters dynr estimates, in report order.
dynr_terms <- c("restoring", "damping", "v0", "mnoise", "dnoise")

# The three a replication is judged to have converged on.
dynr_cells <- c("restoring", "damping", "v0")

# The frame returned when a replication produced no usable estimates.
failed_fit <- data.frame(
  term      = dynr_terms,
  estimate  = NA_real_,
  std.error = NA_real_,
  conf.low  = NA_real_,
  conf.high = NA_real_,
  converged = FALSE,
  stringsAsFactors = FALSE
)

get_estimates <- function(dataset) {

  simdata <- dataset$data
  inits   <- dataset$inits

  start_restoring <- inits[["restoring"]]
  start_damping   <- inits[["damping"]]
  start_v0        <- inits[["v0"]]
  start_mnoise    <- inits[["mnoise"]]

  data <- dynr.data(
    simdata,
    id = "id",
    time = "time",
    observed = "tac"
  )

  measurement <- prep.measurement(
    values.load = matrix(c(1, 0), 1, 2),
    params.load = matrix(c("fixed", "fixed"), 1, 2),
    state.names = c("Position", "Velocity"),
    obs.names = c("tac")
  )

  dynamics <- prep.matrixDynamics(
    values.dyn = matrix(c(0,               1,
                          start_restoring, start_damping),
                        2, 2, byrow = TRUE),
    params.dyn = matrix(c("fixed",     "fixed",
                          "restoring", "damping"), 2, 2, byrow = TRUE),
    isContinuousTime = TRUE
  )

  initial <- prep.initial(
    values.inistate = matrix(c(0, start_v0), 2, 1),
    params.inistate = matrix(c("fixed", "v0"), 2, 1),
    values.inicov   = matrix(0, 2, 2),
    params.inicov   = matrix("fixed", 2, 2)
  )

  # Process noise starts at a small value for convergence.
  noise <- prep.noise(
    values.latent   = diag(c(0, 1e-8), 2),
    params.latent   = diag(c("fixed", "dnoise"), 2),
    values.observed = matrix(start_mnoise, 1, 1),
    params.observed = matrix("mnoise", 1, 1)
  )

  trans <- prep.tfun(
    formula.trans = list(
      restoring ~ -exp(restoring),
      damping   ~ -exp(damping)
    ),
    formula.inv = list(
      restoring ~ log(-restoring),
      damping   ~ log(-damping)
    )
  )

  # dynr's c files go here.
  dir.create("dynrtmp", showWarnings = FALSE)

  model <- dynr.model(
    dynamics    = dynamics,
    measurement = measurement,
    noise       = noise,
    initial     = initial,
    transform   = trans,
    data        = data,
    outfile     = sprintf("dynrtmp/dynr_model_%d.c", Sys.getpid())
  )

  # Try the fit; return the error frame if it failed.
  fit <- try(
    dynr.cook(
      model,
      verbose = FALSE,
      debug_flag = FALSE
    ),
    silent = TRUE
  )

  if (inherits(fit, "try-error")) {
    return(failed_fit)
  }

  # Now we present the dynr results in a tidy dataframe for other functions.
  coefs <- try(summary(fit)$Coefficients, silent = TRUE)

  if (inherits(coefs, "try-error")) {
    return(failed_fit)
  }

  # A fixed parameter gets no row from dynr, so match() leaves it NA.
  rows <- coefs[match(dynr_terms, rownames(coefs)), ]

  out <- data.frame(
    term      = dynr_terms,
    estimate  = rows[["Estimate"]],
    std.error = rows[["Std. Error"]],
    conf.low  = rows[["ci.lower"]],
    conf.high = rows[["ci.upper"]],
    converged = TRUE,
    stringsAsFactors = FALSE
  )

  # Return failed fit with invertible Hessians.
  cells <- out[out$term %in% dynr_cells, ]
  if (any(!is.finite(cells$estimate)) || any(!is.finite(cells$std.error))) {
    return(failed_fit)
  }

  return(out)
}
