# aggregate_results.R
# Run once after all condition jobs (run_jobs.sh) have finished.
# Collects simulation/results/cond_*.rds into one table and writes a
# ready-to-\input booktabs LaTeX table to simulation/tables/table_sim.tex,
# which sections/03_simulation_results.tex pulls in directly.
#
#   Rscript simulation/aggregate_results.R

result_files <- list.files("simulation/results", pattern = "^cond_.*\\.rds$", full.names = TRUE)
stopifnot(length(result_files) > 0)

results <- do.call(rbind, lapply(result_files, readRDS))
results <- results[order(results$n, results$b1), ]

dir.create("simulation/tables", showWarnings = FALSE, recursive = TRUE)

fmt <- function(x, digits = 3) formatC(x, digits = digits, format = "f")

rows <- sprintf(
  "%d & %s & %s & %s & %s & %s & %s \\\\",
  results$n, fmt(results$b1, 2), fmt(results$bias), fmt(results$rmse),
  fmt(results$coverage), fmt(results$power), fmt(results$convergence)
)

tex <- c(
  "% Auto-generated by simulation/aggregate_results.R -- do not edit by hand.",
  "\\begin{table}",
  "  \\caption{Simulation Performance Measures}",
  "  \\label{tab:sim}",
  "  \\begin{tabular}{@{}lrrrrrr@{}}",
  "    \\toprule",
  "    $N$ & True $\\beta_1$ & Bias & RMSE & Coverage & Power & Convergence \\\\",
  "    \\midrule",
  paste0("    ", rows),
  "    \\bottomrule",
  "  \\end{tabular}",
  "  \\tablenote{Bias, RMSE, and 95\\% CI coverage/power are computed over converged replications only. Convergence is the proportion of replications that converged.}",
  "\\end{table}"
)

writeLines(tex, "simulation/tables/table_sim.tex")
