# make_tables.R
# Builds the simulation results table as LaTeX lines. simulation/main.R
# writes them to simulation/tables/tab_sim.tex, \input by
# sections/03_simulation_results.tex.
#
# Pure -- fmt() comes from shared/style.R, which main.R sources first.

#' Builds the simulation results table as LaTeX lines.
#'
#' @param results Data frame from collect_answers(), one row per
#'   condition, supplying `n`, `b1`, and the measure columns.
#' @return Character vector of LaTeX lines, one per element.
make_sim_table <- function(results) {
  rows <- sprintf(
    "%d & %s & %s & %s & %s & %s & %s \\\\",
    results$n, fmt(results$b1, 2), fmt(results$bias), fmt(results$rmse),
    fmt(results$coverage), fmt(results$power), fmt(results$convergence)
  )

  c(
    "% Auto-generated by simulation/main.R -- do not edit by hand.",
    "\\begin{table}",
    "  \\caption{Simulation Performance Measures}",
    "  \\label{tab:sim}",
    "  \\begin{tabular}{@{}lrrrrrr@{}}",
    "    \\toprule",
    "    $N$ & True $\\beta_1$ & Bias & RMSE & Coverage & Power & Convergence \\\\",
    "    \\midrule",
    paste0("    ", rows),
    "    \\bottomrule",
    "  \\end{tabular}",
    "  \\tablenote{Bias, RMSE, and 95\\% CI coverage/power are computed over converged replications only. Convergence is the proportion of replications that converged.}",
    "\\end{table}"
  )
}
