# make_tables.R
# Builds the regression table for dissemination/05_empirical_results.tex.
# fmt() comes from style.R, which main.R sources first.

# Display labels for the model's terms.
# A term without an entry here prints its raw name.
term_labels <- c(
  "(Intercept)"    = "Intercept",
  "x1"             = "$X_1$",
  "grouptreatment" = "Treatment"
)

# Builds the empirical regression table as LaTeX lines.
make_empirical_table <- function(results, labels = term_labels) {
  est <- results$estimates

  rows <- sprintf(
    "%s & %s & %s & %s & [%s, %s] \\\\",
    ifelse(est$term %in% names(labels), labels[est$term], est$term),
    fmt(est$estimate), fmt(est$std.error), fmt(est$p.value),
    fmt(est$conf.low), fmt(est$conf.high)
  )

  c(
    "% Auto-generated by empirical/main.R -- do not edit by hand.",
    "\\begin{table}",
    "  \\caption{Empirical Analysis: Regression Estimates}",
    "  \\label{tab:empirical}",
    "  \\begin{tabular}{@{}lrrrl@{}}",
    "    \\toprule",
    "    Term & $B$ & $SE$ & $p$ & 95\\% CI \\\\",
    "    \\midrule",
    paste0("    ", rows),
    "    \\bottomrule",
    "  \\end{tabular}",
    sprintf("  \\tablenote{$N$ = %d, $R^2$ = %s.}",
            results$n, fmt(results$r_squared, 3)),
    "\\end{table}"
  )
}
