# make_tables.R
# Run after run_analysis.R. Reads empirical/data/processed/results.rds and
# writes a ready-to-\input booktabs LaTeX table to
# empirical/tables/tab_empirical.tex, which sections/05_empirical_results.tex
# pulls in directly.
#
#   Rscript empirical/make_tables.R

results <- readRDS("empirical/data/processed/results.rds")
est <- results$estimates

dir.create("empirical/tables", showWarnings = FALSE, recursive = TRUE)

fmt <- function(x, digits = 3) formatC(x, digits = digits, format = "f")

term_labels <- c(
  "(Intercept)"       = "Intercept",
  "x1"                = "$X_1$",
  "grouptreatment"    = "Treatment"
)

rows <- sprintf(
  "%s & %s & %s & %s & [%s, %s] \\\\",
  ifelse(est$term %in% names(term_labels), term_labels[est$term], est$term),
  fmt(est$estimate), fmt(est$std.error), fmt(est$p.value),
  fmt(est$conf.low), fmt(est$conf.high)
)

tex <- c(
  "% Auto-generated by empirical/make_tables.R -- do not edit by hand.",
  "\\begin{table}",
  "  \\caption{Empirical Analysis: Regression Estimates}",
  "  \\label{tab:empirical}",
  "  \\begin{tabular}{@{}lrrrl@{}}",
  "    \\toprule",
  "    Term & $B$ & $SE$ & $p$ & 95\\% CI \\\\",
  "    \\midrule",
  paste0("    ", rows),
  "    \\bottomrule",
  "  \\end{tabular}",
  sprintf(
    "  \\tablenote{$N$ = %d, $R^2$ = %s.}",
    results$n, fmt(results$r_squared, 3)
  ),
  "\\end{table}"
)

writeLines(tex, "empirical/tables/tab_empirical.tex")
