# make_tables.R
# Builds the regression table as LaTeX lines. empirical/main.R writes
# them to empirical/tables/tab_empirical.tex, \input by
# sections/05_empirical_results.tex.
#
# Pure -- fmt() comes from shared/style.R, which main.R sources first.

# Display labels for the model's terms. A predictor added to
# analyze_dataset() needs an entry here or it prints its raw name.
term_labels <- c(
  "(Intercept)"    = "Intercept",
  "x1"             = "$X_1$",
  "grouptreatment" = "Treatment"
)

#' Builds the empirical regression table as LaTeX lines.
#'
#' @param results Named list from analyze_dataset(), supplying
#'   `estimates`, `n`, and `r_squared`.
#' @param labels Named character vector mapping model terms to display
#'   labels; a term without an entry prints its raw name.
#' @return Character vector of LaTeX lines, one per element.
make_empirical_table <- function(results, labels = term_labels) {
  est <- results$estimates

  rows <- sprintf(
    "%s & %s & %s & %s & [%s, %s] \\\\",
    ifelse(est$term %in% names(labels), labels[est$term], est$term),
    fmt(est$estimate), fmt(est$std.error), fmt(est$p.value),
    fmt(est$conf.low), fmt(est$conf.high)
  )

  c(
    "% Auto-generated by empirical/main.R -- do not edit by hand.",
    "\\begin{table}",
    "  \\caption{Empirical Analysis: Regression Estimates}",
    "  \\label{tab:empirical}",
    "  \\begin{tabular}{@{}lrrrl@{}}",
    "    \\toprule",
    "    Term & $B$ & $SE$ & $p$ & 95\\% CI \\\\",
    "    \\midrule",
    paste0("    ", rows),
    "    \\bottomrule",
    "  \\end{tabular}",
    sprintf("  \\tablenote{$N$ = %d, $R^2$ = %s.}",
            results$n, fmt(results$r_squared, 3)),
    "\\end{table}"
  )
}
